/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AppAvailabilityV2RelationshipsTerritoryAvailabilitiesDataInner;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities
 */
public class AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilitiesTest {
    private final AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities model = new AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities();

    /**
     * Model tests for AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities
     */
    @Test
    public void testAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities() {
        // TODO: test AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
