/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.client.model.AppCustomProductPage;
import org.openapitools.client.model.AppCustomProductPageLocalization;
import org.openapitools.client.model.AppCustomProductPageLocalizationAttributes;
import org.openapitools.client.model.AppCustomProductPageLocalizationRelationships;
import org.openapitools.client.model.ResourceLinks;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AppCustomProductPageVersionsResponseIncludedInner
 */
public class AppCustomProductPageVersionsResponseIncludedInnerTest {
    private final AppCustomProductPageVersionsResponseIncludedInner model = new AppCustomProductPageVersionsResponseIncludedInner();

    /**
     * Model tests for AppCustomProductPageVersionsResponseIncludedInner
     */
    @Test
    public void testAppCustomProductPageVersionsResponseIncludedInner() {
        // TODO: test AppCustomProductPageVersionsResponseIncludedInner
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'relationships'
     */
    @Test
    public void relationshipsTest() {
        // TODO: test relationships
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
