/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AppEventAttributesTerritorySchedulesInner
 */
public class AppEventAttributesTerritorySchedulesInnerTest {
    private final AppEventAttributesTerritorySchedulesInner model = new AppEventAttributesTerritorySchedulesInner();

    /**
     * Model tests for AppEventAttributesTerritorySchedulesInner
     */
    @Test
    public void testAppEventAttributesTerritorySchedulesInner() {
        // TODO: test AppEventAttributesTerritorySchedulesInner
    }

    /**
     * Test the property 'territories'
     */
    @Test
    public void territoriesTest() {
        // TODO: test territories
    }

    /**
     * Test the property 'publishStart'
     */
    @Test
    public void publishStartTest() {
        // TODO: test publishStart
    }

    /**
     * Test the property 'eventStart'
     */
    @Test
    public void eventStartTest() {
        // TODO: test eventStart
    }

    /**
     * Test the property 'eventEnd'
     */
    @Test
    public void eventEndTest() {
        // TODO: test eventEnd
    }

}
