/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.client.model.AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion;
import org.openapitools.client.model.AppCustomProductPageLocalizationRelationshipsAppPreviewSets;
import org.openapitools.client.model.AppCustomProductPageLocalizationRelationshipsAppScreenshotSets;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AppStoreVersionLocalizationRelationships
 */
public class AppStoreVersionLocalizationRelationshipsTest {
    private final AppStoreVersionLocalizationRelationships model = new AppStoreVersionLocalizationRelationships();

    /**
     * Model tests for AppStoreVersionLocalizationRelationships
     */
    @Test
    public void testAppStoreVersionLocalizationRelationships() {
        // TODO: test AppStoreVersionLocalizationRelationships
    }

    /**
     * Test the property 'appStoreVersion'
     */
    @Test
    public void appStoreVersionTest() {
        // TODO: test appStoreVersion
    }

    /**
     * Test the property 'appScreenshotSets'
     */
    @Test
    public void appScreenshotSetsTest() {
        // TODO: test appScreenshotSets
    }

    /**
     * Test the property 'appPreviewSets'
     */
    @Test
    public void appPreviewSetsTest() {
        // TODO: test appPreviewSets
    }

}
