/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AppStoreVersionLocalizationAttributes
 */
public class AppStoreVersionLocalizationAttributesTest {
    private final AppStoreVersionLocalizationAttributes model = new AppStoreVersionLocalizationAttributes();

    /**
     * Model tests for AppStoreVersionLocalizationAttributes
     */
    @Test
    public void testAppStoreVersionLocalizationAttributes() {
        // TODO: test AppStoreVersionLocalizationAttributes
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'locale'
     */
    @Test
    public void localeTest() {
        // TODO: test locale
    }

    /**
     * Test the property 'keywords'
     */
    @Test
    public void keywordsTest() {
        // TODO: test keywords
    }

    /**
     * Test the property 'marketingUrl'
     */
    @Test
    public void marketingUrlTest() {
        // TODO: test marketingUrl
    }

    /**
     * Test the property 'promotionalText'
     */
    @Test
    public void promotionalTextTest() {
        // TODO: test promotionalText
    }

    /**
     * Test the property 'supportUrl'
     */
    @Test
    public void supportUrlTest() {
        // TODO: test supportUrl
    }

    /**
     * Test the property 'whatsNew'
     */
    @Test
    public void whatsNewTest() {
        // TODO: test whatsNew
    }

}
