/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CiIssueCounts
 */
public class CiIssueCountsTest {
    private final CiIssueCounts model = new CiIssueCounts();

    /**
     * Model tests for CiIssueCounts
     */
    @Test
    public void testCiIssueCounts() {
        // TODO: test CiIssueCounts
    }

    /**
     * Test the property 'analyzerWarnings'
     */
    @Test
    public void analyzerWarningsTest() {
        // TODO: test analyzerWarnings
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'testFailures'
     */
    @Test
    public void testFailuresTest() {
        // TODO: test testFailures
    }

    /**
     * Test the property 'warnings'
     */
    @Test
    public void warningsTest() {
        // TODO: test warnings
    }

}
