/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CiTestDestinationKind;
import org.openapitools.client.model.CiXcodeVersionAttributesTestDestinationsInnerAvailableRuntimesInner;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CiXcodeVersionAttributesTestDestinationsInner
 */
public class CiXcodeVersionAttributesTestDestinationsInnerTest {
    private final CiXcodeVersionAttributesTestDestinationsInner model = new CiXcodeVersionAttributesTestDestinationsInner();

    /**
     * Model tests for CiXcodeVersionAttributesTestDestinationsInner
     */
    @Test
    public void testCiXcodeVersionAttributesTestDestinationsInner() {
        // TODO: test CiXcodeVersionAttributesTestDestinationsInner
    }

    /**
     * Test the property 'deviceTypeName'
     */
    @Test
    public void deviceTypeNameTest() {
        // TODO: test deviceTypeName
    }

    /**
     * Test the property 'deviceTypeIdentifier'
     */
    @Test
    public void deviceTypeIdentifierTest() {
        // TODO: test deviceTypeIdentifier
    }

    /**
     * Test the property 'availableRuntimes'
     */
    @Test
    public void availableRuntimesTest() {
        // TODO: test availableRuntimes
    }

    /**
     * Test the property 'kind'
     */
    @Test
    public void kindTest() {
        // TODO: test kind
    }

}
