/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.client.model.GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPoints;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GameCenterMatchmakingQueueSizesV1MetricResponseDataInner
 */
public class GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerTest {
    private final GameCenterMatchmakingQueueSizesV1MetricResponseDataInner model = new GameCenterMatchmakingQueueSizesV1MetricResponseDataInner();

    /**
     * Model tests for GameCenterMatchmakingQueueSizesV1MetricResponseDataInner
     */
    @Test
    public void testGameCenterMatchmakingQueueSizesV1MetricResponseDataInner() {
        // TODO: test GameCenterMatchmakingQueueSizesV1MetricResponseDataInner
    }

    /**
     * Test the property 'dataPoints'
     */
    @Test
    public void dataPointsTest() {
        // TODO: test dataPoints
    }

    /**
     * Test the property 'granularity'
     */
    @Test
    public void granularityTest() {
        // TODO: test granularity
    }

}
