/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.client.model.GameCenterMatchmakingQueueRelationshipsRuleSet;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GameCenterMatchmakingQueueRelationships
 */
public class GameCenterMatchmakingQueueRelationshipsTest {
    private final GameCenterMatchmakingQueueRelationships model = new GameCenterMatchmakingQueueRelationships();

    /**
     * Model tests for GameCenterMatchmakingQueueRelationships
     */
    @Test
    public void testGameCenterMatchmakingQueueRelationships() {
        // TODO: test GameCenterMatchmakingQueueRelationships
    }

    /**
     * Test the property 'ruleSet'
     */
    @Test
    public void ruleSetTest() {
        // TODO: test ruleSet
    }

    /**
     * Test the property 'experimentRuleSet'
     */
    @Test
    public void experimentRuleSetTest() {
        // TODO: test experimentRuleSet
    }

}
