/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.client.model.Location;
import org.openapitools.client.model.Platform;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GameCenterMatchmakingTestRequestInlineCreateAttributes
 */
public class GameCenterMatchmakingTestRequestInlineCreateAttributesTest {
    private final GameCenterMatchmakingTestRequestInlineCreateAttributes model = new GameCenterMatchmakingTestRequestInlineCreateAttributes();

    /**
     * Model tests for GameCenterMatchmakingTestRequestInlineCreateAttributes
     */
    @Test
    public void testGameCenterMatchmakingTestRequestInlineCreateAttributes() {
        // TODO: test GameCenterMatchmakingTestRequestInlineCreateAttributes
    }

    /**
     * Test the property 'requestName'
     */
    @Test
    public void requestNameTest() {
        // TODO: test requestName
    }

    /**
     * Test the property 'secondsInQueue'
     */
    @Test
    public void secondsInQueueTest() {
        // TODO: test secondsInQueue
    }

    /**
     * Test the property 'locale'
     */
    @Test
    public void localeTest() {
        // TODO: test locale
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'minPlayers'
     */
    @Test
    public void minPlayersTest() {
        // TODO: test minPlayers
    }

    /**
     * Test the property 'maxPlayers'
     */
    @Test
    public void maxPlayersTest() {
        // TODO: test maxPlayers
    }

    /**
     * Test the property 'playerCount'
     */
    @Test
    public void playerCountTest() {
        // TODO: test playerCount
    }

    /**
     * Test the property 'bundleId'
     */
    @Test
    public void bundleIdTest() {
        // TODO: test bundleId
    }

    /**
     * Test the property 'platform'
     */
    @Test
    public void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'appVersion'
     */
    @Test
    public void appVersionTest() {
        // TODO: test appVersion
    }

}
