/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PromotedPurchaseCreateRequestDataAttributes
 */
public class PromotedPurchaseCreateRequestDataAttributesTest {
    private final PromotedPurchaseCreateRequestDataAttributes model = new PromotedPurchaseCreateRequestDataAttributes();

    /**
     * Model tests for PromotedPurchaseCreateRequestDataAttributes
     */
    @Test
    public void testPromotedPurchaseCreateRequestDataAttributes() {
        // TODO: test PromotedPurchaseCreateRequestDataAttributes
    }

    /**
     * Test the property 'visibleForAllUsers'
     */
    @Test
    public void visibleForAllUsersTest() {
        // TODO: test visibleForAllUsers
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

}
