/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.client.model.TerritoryCode;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SandboxTesterV2Attributes
 */
public class SandboxTesterV2AttributesTest {
    private final SandboxTesterV2Attributes model = new SandboxTesterV2Attributes();

    /**
     * Model tests for SandboxTesterV2Attributes
     */
    @Test
    public void testSandboxTesterV2Attributes() {
        // TODO: test SandboxTesterV2Attributes
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'acAccountName'
     */
    @Test
    public void acAccountNameTest() {
        // TODO: test acAccountName
    }

    /**
     * Test the property 'territory'
     */
    @Test
    public void territoryTest() {
        // TODO: test territory
    }

    /**
     * Test the property 'applePayCompatible'
     */
    @Test
    public void applePayCompatibleTest() {
        // TODO: test applePayCompatible
    }

    /**
     * Test the property 'interruptPurchases'
     */
    @Test
    public void interruptPurchasesTest() {
        // TODO: test interruptPurchases
    }

    /**
     * Test the property 'subscriptionRenewalRate'
     */
    @Test
    public void subscriptionRenewalRateTest() {
        // TODO: test subscriptionRenewalRate
    }

}
