/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TerritoryAvailabilityAttributes
 */
public class TerritoryAvailabilityAttributesTest {
    private final TerritoryAvailabilityAttributes model = new TerritoryAvailabilityAttributes();

    /**
     * Model tests for TerritoryAvailabilityAttributes
     */
    @Test
    public void testTerritoryAvailabilityAttributes() {
        // TODO: test TerritoryAvailabilityAttributes
    }

    /**
     * Test the property 'available'
     */
    @Test
    public void availableTest() {
        // TODO: test available
    }

    /**
     * Test the property 'releaseDate'
     */
    @Test
    public void releaseDateTest() {
        // TODO: test releaseDate
    }

    /**
     * Test the property 'preOrderEnabled'
     */
    @Test
    public void preOrderEnabledTest() {
        // TODO: test preOrderEnabled
    }

    /**
     * Test the property 'preOrderPublishDate'
     */
    @Test
    public void preOrderPublishDateTest() {
        // TODO: test preOrderPublishDate
    }

    /**
     * Test the property 'contentStatuses'
     */
    @Test
    public void contentStatusesTest() {
        // TODO: test contentStatuses
    }

}
