/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.client.model.AppCustomProductPageVersion;
import org.openapitools.client.model.AppPreviewSet;
import org.openapitools.client.model.AppPreviewSetAttributes;
import org.openapitools.client.model.AppPreviewSetRelationships;
import org.openapitools.client.model.AppScreenshotSet;
import org.openapitools.client.model.ResourceLinks;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.client.JSON;

import com.fasterxml.jackson.core.type.TypeReference;

import jakarta.ws.rs.core.GenericType;
import jakarta.ws.rs.core.Response;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import org.openapitools.client.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-26T23:41:20.466109+03:00[Europe/Moscow]", comments = "Generator version: 7.6.0")
@JsonDeserialize(using = AppCustomProductPageLocalizationsResponseIncludedInner.AppCustomProductPageLocalizationsResponseIncludedInnerDeserializer.class)
@JsonSerialize(using = AppCustomProductPageLocalizationsResponseIncludedInner.AppCustomProductPageLocalizationsResponseIncludedInnerSerializer.class)
public class AppCustomProductPageLocalizationsResponseIncludedInner extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(AppCustomProductPageLocalizationsResponseIncludedInner.class.getName());

    public static class AppCustomProductPageLocalizationsResponseIncludedInnerSerializer extends StdSerializer<AppCustomProductPageLocalizationsResponseIncludedInner> {
        public AppCustomProductPageLocalizationsResponseIncludedInnerSerializer(Class<AppCustomProductPageLocalizationsResponseIncludedInner> t) {
            super(t);
        }

        public AppCustomProductPageLocalizationsResponseIncludedInnerSerializer() {
            this(null);
        }

        @Override
        public void serialize(AppCustomProductPageLocalizationsResponseIncludedInner value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class AppCustomProductPageLocalizationsResponseIncludedInnerDeserializer extends StdDeserializer<AppCustomProductPageLocalizationsResponseIncludedInner> {
        public AppCustomProductPageLocalizationsResponseIncludedInnerDeserializer() {
            this(AppCustomProductPageLocalizationsResponseIncludedInner.class);
        }

        public AppCustomProductPageLocalizationsResponseIncludedInnerDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public AppCustomProductPageLocalizationsResponseIncludedInner deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize AppCustomProductPageVersion
            try {
                boolean attemptParsing = true;
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(AppCustomProductPageVersion.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'AppCustomProductPageVersion'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'AppCustomProductPageVersion'", e);
            }

            // deserialize AppScreenshotSet
            try {
                boolean attemptParsing = true;
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(AppScreenshotSet.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'AppScreenshotSet'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'AppScreenshotSet'", e);
            }

            // deserialize AppPreviewSet
            try {
                boolean attemptParsing = true;
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(AppPreviewSet.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'AppPreviewSet'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'AppPreviewSet'", e);
            }

            if (match == 1) {
                AppCustomProductPageLocalizationsResponseIncludedInner ret = new AppCustomProductPageLocalizationsResponseIncludedInner();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for AppCustomProductPageLocalizationsResponseIncludedInner: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public AppCustomProductPageLocalizationsResponseIncludedInner getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "AppCustomProductPageLocalizationsResponseIncludedInner cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType> schemas = new HashMap<>();

    public AppCustomProductPageLocalizationsResponseIncludedInner() {
        super("oneOf", Boolean.FALSE);
    }

    public AppCustomProductPageLocalizationsResponseIncludedInner(AppCustomProductPageVersion o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public AppCustomProductPageLocalizationsResponseIncludedInner(AppScreenshotSet o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public AppCustomProductPageLocalizationsResponseIncludedInner(AppPreviewSet o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("AppCustomProductPageVersion", new GenericType<AppCustomProductPageVersion>() {
        });
        schemas.put("AppPreviewSet", new GenericType<AppPreviewSet>() {
        });
        schemas.put("AppScreenshotSet", new GenericType<AppScreenshotSet>() {
        });
        JSON.registerDescendants(AppCustomProductPageLocalizationsResponseIncludedInner.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return AppCustomProductPageLocalizationsResponseIncludedInner.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * AppCustomProductPageVersion, AppPreviewSet, AppScreenshotSet
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(AppCustomProductPageVersion.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(AppScreenshotSet.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(AppPreviewSet.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be AppCustomProductPageVersion, AppPreviewSet, AppScreenshotSet");
    }

    /**
     * Get the actual instance, which can be the following:
     * AppCustomProductPageVersion, AppPreviewSet, AppScreenshotSet
     *
     * @return The actual instance (AppCustomProductPageVersion, AppPreviewSet, AppScreenshotSet)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `AppCustomProductPageVersion`. If the actual instance is not `AppCustomProductPageVersion`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AppCustomProductPageVersion`
     * @throws ClassCastException if the instance is not `AppCustomProductPageVersion`
     */
    public AppCustomProductPageVersion getAppCustomProductPageVersion() throws ClassCastException {
        return (AppCustomProductPageVersion)super.getActualInstance();
    }

    /**
     * Get the actual instance of `AppScreenshotSet`. If the actual instance is not `AppScreenshotSet`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AppScreenshotSet`
     * @throws ClassCastException if the instance is not `AppScreenshotSet`
     */
    public AppScreenshotSet getAppScreenshotSet() throws ClassCastException {
        return (AppScreenshotSet)super.getActualInstance();
    }

    /**
     * Get the actual instance of `AppPreviewSet`. If the actual instance is not `AppPreviewSet`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AppPreviewSet`
     * @throws ClassCastException if the instance is not `AppPreviewSet`
     */
    public AppPreviewSet getAppPreviewSet() throws ClassCastException {
        return (AppPreviewSet)super.getActualInstance();
    }

}

