/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import org.openapitools.client.model.AppClipAction;
import org.openapitools.client.model.AppClipAdvancedExperienceAttributesPlace;
import org.openapitools.client.model.AppClipAdvancedExperienceLanguage;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.client.JSON;


/**
 * AppClipAdvancedExperienceAttributes
 */
@JsonPropertyOrder({
  AppClipAdvancedExperienceAttributes.JSON_PROPERTY_LINK,
  AppClipAdvancedExperienceAttributes.JSON_PROPERTY_VERSION,
  AppClipAdvancedExperienceAttributes.JSON_PROPERTY_STATUS,
  AppClipAdvancedExperienceAttributes.JSON_PROPERTY_ACTION,
  AppClipAdvancedExperienceAttributes.JSON_PROPERTY_IS_POWERED_BY,
  AppClipAdvancedExperienceAttributes.JSON_PROPERTY_PLACE,
  AppClipAdvancedExperienceAttributes.JSON_PROPERTY_PLACE_STATUS,
  AppClipAdvancedExperienceAttributes.JSON_PROPERTY_BUSINESS_CATEGORY,
  AppClipAdvancedExperienceAttributes.JSON_PROPERTY_DEFAULT_LANGUAGE
})
@JsonTypeName("AppClipAdvancedExperience_attributes")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-26T23:41:20.466109+03:00[Europe/Moscow]", comments = "Generator version: 7.6.0")
public class AppClipAdvancedExperienceAttributes {
  public static final String JSON_PROPERTY_LINK = "link";
  private URI link;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Integer version;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    RECEIVED("RECEIVED"),
    
    DEACTIVATED("DEACTIVATED"),
    
    APP_TRANSFER_IN_PROGRESS("APP_TRANSFER_IN_PROGRESS");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_ACTION = "action";
  private AppClipAction action;

  public static final String JSON_PROPERTY_IS_POWERED_BY = "isPoweredBy";
  private Boolean isPoweredBy;

  public static final String JSON_PROPERTY_PLACE = "place";
  private AppClipAdvancedExperienceAttributesPlace place;

  /**
   * Gets or Sets placeStatus
   */
  public enum PlaceStatusEnum {
    PENDING("PENDING"),
    
    MATCHED("MATCHED"),
    
    NO_MATCH("NO_MATCH");

    private String value;

    PlaceStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PlaceStatusEnum fromValue(String value) {
      for (PlaceStatusEnum b : PlaceStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PLACE_STATUS = "placeStatus";
  private PlaceStatusEnum placeStatus;

  /**
   * Gets or Sets businessCategory
   */
  public enum BusinessCategoryEnum {
    AUTOMOTIVE("AUTOMOTIVE"),
    
    BEAUTY("BEAUTY"),
    
    BIKES("BIKES"),
    
    BOOKS("BOOKS"),
    
    CASINO("CASINO"),
    
    EDUCATION("EDUCATION"),
    
    EDUCATION_JAPAN("EDUCATION_JAPAN"),
    
    ENTERTAINMENT("ENTERTAINMENT"),
    
    EV_CHARGER("EV_CHARGER"),
    
    FINANCIAL_USD("FINANCIAL_USD"),
    
    FINANCIAL_CNY("FINANCIAL_CNY"),
    
    FINANCIAL_GBP("FINANCIAL_GBP"),
    
    FINANCIAL_JPY("FINANCIAL_JPY"),
    
    FINANCIAL_EUR("FINANCIAL_EUR"),
    
    FITNESS("FITNESS"),
    
    FOOD_AND_DRINK("FOOD_AND_DRINK"),
    
    GAS("GAS"),
    
    GROCERY("GROCERY"),
    
    HEALTH_AND_MEDICAL("HEALTH_AND_MEDICAL"),
    
    HOTEL_AND_TRAVEL("HOTEL_AND_TRAVEL"),
    
    MUSIC("MUSIC"),
    
    PARKING("PARKING"),
    
    PET_SERVICES("PET_SERVICES"),
    
    PROFESSIONAL_SERVICES("PROFESSIONAL_SERVICES"),
    
    SHOPPING("SHOPPING"),
    
    TICKETING("TICKETING"),
    
    TRANSIT("TRANSIT");

    private String value;

    BusinessCategoryEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static BusinessCategoryEnum fromValue(String value) {
      for (BusinessCategoryEnum b : BusinessCategoryEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_BUSINESS_CATEGORY = "businessCategory";
  private BusinessCategoryEnum businessCategory;

  public static final String JSON_PROPERTY_DEFAULT_LANGUAGE = "defaultLanguage";
  private AppClipAdvancedExperienceLanguage defaultLanguage;

  public AppClipAdvancedExperienceAttributes() { 
  }

  public AppClipAdvancedExperienceAttributes link(URI link) {
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLink(URI link) {
    this.link = link;
  }


  public AppClipAdvancedExperienceAttributes version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(Integer version) {
    this.version = version;
  }


  public AppClipAdvancedExperienceAttributes status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public AppClipAdvancedExperienceAttributes action(AppClipAction action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppClipAction getAction() {
    return action;
  }


  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAction(AppClipAction action) {
    this.action = action;
  }


  public AppClipAdvancedExperienceAttributes isPoweredBy(Boolean isPoweredBy) {
    this.isPoweredBy = isPoweredBy;
    return this;
  }

   /**
   * Get isPoweredBy
   * @return isPoweredBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_POWERED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsPoweredBy() {
    return isPoweredBy;
  }


  @JsonProperty(JSON_PROPERTY_IS_POWERED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsPoweredBy(Boolean isPoweredBy) {
    this.isPoweredBy = isPoweredBy;
  }


  public AppClipAdvancedExperienceAttributes place(AppClipAdvancedExperienceAttributesPlace place) {
    this.place = place;
    return this;
  }

   /**
   * Get place
   * @return place
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppClipAdvancedExperienceAttributesPlace getPlace() {
    return place;
  }


  @JsonProperty(JSON_PROPERTY_PLACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlace(AppClipAdvancedExperienceAttributesPlace place) {
    this.place = place;
  }


  public AppClipAdvancedExperienceAttributes placeStatus(PlaceStatusEnum placeStatus) {
    this.placeStatus = placeStatus;
    return this;
  }

   /**
   * Get placeStatus
   * @return placeStatus
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLACE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PlaceStatusEnum getPlaceStatus() {
    return placeStatus;
  }


  @JsonProperty(JSON_PROPERTY_PLACE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlaceStatus(PlaceStatusEnum placeStatus) {
    this.placeStatus = placeStatus;
  }


  public AppClipAdvancedExperienceAttributes businessCategory(BusinessCategoryEnum businessCategory) {
    this.businessCategory = businessCategory;
    return this;
  }

   /**
   * Get businessCategory
   * @return businessCategory
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUSINESS_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BusinessCategoryEnum getBusinessCategory() {
    return businessCategory;
  }


  @JsonProperty(JSON_PROPERTY_BUSINESS_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBusinessCategory(BusinessCategoryEnum businessCategory) {
    this.businessCategory = businessCategory;
  }


  public AppClipAdvancedExperienceAttributes defaultLanguage(AppClipAdvancedExperienceLanguage defaultLanguage) {
    this.defaultLanguage = defaultLanguage;
    return this;
  }

   /**
   * Get defaultLanguage
   * @return defaultLanguage
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppClipAdvancedExperienceLanguage getDefaultLanguage() {
    return defaultLanguage;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultLanguage(AppClipAdvancedExperienceLanguage defaultLanguage) {
    this.defaultLanguage = defaultLanguage;
  }


  /**
   * Return true if this AppClipAdvancedExperience_attributes object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppClipAdvancedExperienceAttributes appClipAdvancedExperienceAttributes = (AppClipAdvancedExperienceAttributes) o;
    return Objects.equals(this.link, appClipAdvancedExperienceAttributes.link) &&
        Objects.equals(this.version, appClipAdvancedExperienceAttributes.version) &&
        Objects.equals(this.status, appClipAdvancedExperienceAttributes.status) &&
        Objects.equals(this.action, appClipAdvancedExperienceAttributes.action) &&
        Objects.equals(this.isPoweredBy, appClipAdvancedExperienceAttributes.isPoweredBy) &&
        Objects.equals(this.place, appClipAdvancedExperienceAttributes.place) &&
        Objects.equals(this.placeStatus, appClipAdvancedExperienceAttributes.placeStatus) &&
        Objects.equals(this.businessCategory, appClipAdvancedExperienceAttributes.businessCategory) &&
        Objects.equals(this.defaultLanguage, appClipAdvancedExperienceAttributes.defaultLanguage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(link, version, status, action, isPoweredBy, place, placeStatus, businessCategory, defaultLanguage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppClipAdvancedExperienceAttributes {\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    isPoweredBy: ").append(toIndentedString(isPoweredBy)).append("\n");
    sb.append("    place: ").append(toIndentedString(place)).append("\n");
    sb.append("    placeStatus: ").append(toIndentedString(placeStatus)).append("\n");
    sb.append("    businessCategory: ").append(toIndentedString(businessCategory)).append("\n");
    sb.append("    defaultLanguage: ").append(toIndentedString(defaultLanguage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

