/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.client.model.AppClipAdvancedExperienceRelationshipsAppClip;
import org.openapitools.client.model.AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail;
import org.openapitools.client.model.AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizations;
import org.openapitools.client.model.AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.client.JSON;


/**
 * AppClipDefaultExperienceRelationships
 */
@JsonPropertyOrder({
  AppClipDefaultExperienceRelationships.JSON_PROPERTY_APP_CLIP,
  AppClipDefaultExperienceRelationships.JSON_PROPERTY_RELEASE_WITH_APP_STORE_VERSION,
  AppClipDefaultExperienceRelationships.JSON_PROPERTY_APP_CLIP_DEFAULT_EXPERIENCE_LOCALIZATIONS,
  AppClipDefaultExperienceRelationships.JSON_PROPERTY_APP_CLIP_APP_STORE_REVIEW_DETAIL
})
@JsonTypeName("AppClipDefaultExperience_relationships")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-26T23:41:20.466109+03:00[Europe/Moscow]", comments = "Generator version: 7.6.0")
public class AppClipDefaultExperienceRelationships {
  public static final String JSON_PROPERTY_APP_CLIP = "appClip";
  private AppClipAdvancedExperienceRelationshipsAppClip appClip;

  public static final String JSON_PROPERTY_RELEASE_WITH_APP_STORE_VERSION = "releaseWithAppStoreVersion";
  private AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion releaseWithAppStoreVersion;

  public static final String JSON_PROPERTY_APP_CLIP_DEFAULT_EXPERIENCE_LOCALIZATIONS = "appClipDefaultExperienceLocalizations";
  private AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizations appClipDefaultExperienceLocalizations;

  public static final String JSON_PROPERTY_APP_CLIP_APP_STORE_REVIEW_DETAIL = "appClipAppStoreReviewDetail";
  private AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail appClipAppStoreReviewDetail;

  public AppClipDefaultExperienceRelationships() { 
  }

  public AppClipDefaultExperienceRelationships appClip(AppClipAdvancedExperienceRelationshipsAppClip appClip) {
    this.appClip = appClip;
    return this;
  }

   /**
   * Get appClip
   * @return appClip
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APP_CLIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppClipAdvancedExperienceRelationshipsAppClip getAppClip() {
    return appClip;
  }


  @JsonProperty(JSON_PROPERTY_APP_CLIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppClip(AppClipAdvancedExperienceRelationshipsAppClip appClip) {
    this.appClip = appClip;
  }


  public AppClipDefaultExperienceRelationships releaseWithAppStoreVersion(AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion releaseWithAppStoreVersion) {
    this.releaseWithAppStoreVersion = releaseWithAppStoreVersion;
    return this;
  }

   /**
   * Get releaseWithAppStoreVersion
   * @return releaseWithAppStoreVersion
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELEASE_WITH_APP_STORE_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion getReleaseWithAppStoreVersion() {
    return releaseWithAppStoreVersion;
  }


  @JsonProperty(JSON_PROPERTY_RELEASE_WITH_APP_STORE_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReleaseWithAppStoreVersion(AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion releaseWithAppStoreVersion) {
    this.releaseWithAppStoreVersion = releaseWithAppStoreVersion;
  }


  public AppClipDefaultExperienceRelationships appClipDefaultExperienceLocalizations(AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizations appClipDefaultExperienceLocalizations) {
    this.appClipDefaultExperienceLocalizations = appClipDefaultExperienceLocalizations;
    return this;
  }

   /**
   * Get appClipDefaultExperienceLocalizations
   * @return appClipDefaultExperienceLocalizations
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APP_CLIP_DEFAULT_EXPERIENCE_LOCALIZATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizations getAppClipDefaultExperienceLocalizations() {
    return appClipDefaultExperienceLocalizations;
  }


  @JsonProperty(JSON_PROPERTY_APP_CLIP_DEFAULT_EXPERIENCE_LOCALIZATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppClipDefaultExperienceLocalizations(AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizations appClipDefaultExperienceLocalizations) {
    this.appClipDefaultExperienceLocalizations = appClipDefaultExperienceLocalizations;
  }


  public AppClipDefaultExperienceRelationships appClipAppStoreReviewDetail(AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail appClipAppStoreReviewDetail) {
    this.appClipAppStoreReviewDetail = appClipAppStoreReviewDetail;
    return this;
  }

   /**
   * Get appClipAppStoreReviewDetail
   * @return appClipAppStoreReviewDetail
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APP_CLIP_APP_STORE_REVIEW_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail getAppClipAppStoreReviewDetail() {
    return appClipAppStoreReviewDetail;
  }


  @JsonProperty(JSON_PROPERTY_APP_CLIP_APP_STORE_REVIEW_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppClipAppStoreReviewDetail(AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail appClipAppStoreReviewDetail) {
    this.appClipAppStoreReviewDetail = appClipAppStoreReviewDetail;
  }


  /**
   * Return true if this AppClipDefaultExperience_relationships object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppClipDefaultExperienceRelationships appClipDefaultExperienceRelationships = (AppClipDefaultExperienceRelationships) o;
    return Objects.equals(this.appClip, appClipDefaultExperienceRelationships.appClip) &&
        Objects.equals(this.releaseWithAppStoreVersion, appClipDefaultExperienceRelationships.releaseWithAppStoreVersion) &&
        Objects.equals(this.appClipDefaultExperienceLocalizations, appClipDefaultExperienceRelationships.appClipDefaultExperienceLocalizations) &&
        Objects.equals(this.appClipAppStoreReviewDetail, appClipDefaultExperienceRelationships.appClipAppStoreReviewDetail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appClip, releaseWithAppStoreVersion, appClipDefaultExperienceLocalizations, appClipAppStoreReviewDetail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppClipDefaultExperienceRelationships {\n");
    sb.append("    appClip: ").append(toIndentedString(appClip)).append("\n");
    sb.append("    releaseWithAppStoreVersion: ").append(toIndentedString(releaseWithAppStoreVersion)).append("\n");
    sb.append("    appClipDefaultExperienceLocalizations: ").append(toIndentedString(appClipDefaultExperienceLocalizations)).append("\n");
    sb.append("    appClipAppStoreReviewDetail: ").append(toIndentedString(appClipAppStoreReviewDetail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

