/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.client.model.AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersion;
import org.openapitools.client.model.AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationshipsAppStoreVersionExperimentTreatment;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.client.JSON;


/**
 * AppStoreVersionPromotionCreateRequestDataRelationships
 */
@JsonPropertyOrder({
  AppStoreVersionPromotionCreateRequestDataRelationships.JSON_PROPERTY_APP_STORE_VERSION,
  AppStoreVersionPromotionCreateRequestDataRelationships.JSON_PROPERTY_APP_STORE_VERSION_EXPERIMENT_TREATMENT
})
@JsonTypeName("AppStoreVersionPromotionCreateRequest_data_relationships")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-26T23:41:20.466109+03:00[Europe/Moscow]", comments = "Generator version: 7.6.0")
public class AppStoreVersionPromotionCreateRequestDataRelationships {
  public static final String JSON_PROPERTY_APP_STORE_VERSION = "appStoreVersion";
  private AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersion appStoreVersion;

  public static final String JSON_PROPERTY_APP_STORE_VERSION_EXPERIMENT_TREATMENT = "appStoreVersionExperimentTreatment";
  private AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationshipsAppStoreVersionExperimentTreatment appStoreVersionExperimentTreatment;

  public AppStoreVersionPromotionCreateRequestDataRelationships() { 
  }

  public AppStoreVersionPromotionCreateRequestDataRelationships appStoreVersion(AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersion appStoreVersion) {
    this.appStoreVersion = appStoreVersion;
    return this;
  }

   /**
   * Get appStoreVersion
   * @return appStoreVersion
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_APP_STORE_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersion getAppStoreVersion() {
    return appStoreVersion;
  }


  @JsonProperty(JSON_PROPERTY_APP_STORE_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppStoreVersion(AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersion appStoreVersion) {
    this.appStoreVersion = appStoreVersion;
  }


  public AppStoreVersionPromotionCreateRequestDataRelationships appStoreVersionExperimentTreatment(AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationshipsAppStoreVersionExperimentTreatment appStoreVersionExperimentTreatment) {
    this.appStoreVersionExperimentTreatment = appStoreVersionExperimentTreatment;
    return this;
  }

   /**
   * Get appStoreVersionExperimentTreatment
   * @return appStoreVersionExperimentTreatment
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_APP_STORE_VERSION_EXPERIMENT_TREATMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationshipsAppStoreVersionExperimentTreatment getAppStoreVersionExperimentTreatment() {
    return appStoreVersionExperimentTreatment;
  }


  @JsonProperty(JSON_PROPERTY_APP_STORE_VERSION_EXPERIMENT_TREATMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppStoreVersionExperimentTreatment(AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationshipsAppStoreVersionExperimentTreatment appStoreVersionExperimentTreatment) {
    this.appStoreVersionExperimentTreatment = appStoreVersionExperimentTreatment;
  }


  /**
   * Return true if this AppStoreVersionPromotionCreateRequest_data_relationships object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppStoreVersionPromotionCreateRequestDataRelationships appStoreVersionPromotionCreateRequestDataRelationships = (AppStoreVersionPromotionCreateRequestDataRelationships) o;
    return Objects.equals(this.appStoreVersion, appStoreVersionPromotionCreateRequestDataRelationships.appStoreVersion) &&
        Objects.equals(this.appStoreVersionExperimentTreatment, appStoreVersionPromotionCreateRequestDataRelationships.appStoreVersionExperimentTreatment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appStoreVersion, appStoreVersionExperimentTreatment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppStoreVersionPromotionCreateRequestDataRelationships {\n");
    sb.append("    appStoreVersion: ").append(toIndentedString(appStoreVersion)).append("\n");
    sb.append("    appStoreVersionExperimentTreatment: ").append(toIndentedString(appStoreVersionExperimentTreatment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

