/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.client.JSON;


/**
 * CapabilityOption
 */
@JsonPropertyOrder({
  CapabilityOption.JSON_PROPERTY_KEY,
  CapabilityOption.JSON_PROPERTY_NAME,
  CapabilityOption.JSON_PROPERTY_DESCRIPTION,
  CapabilityOption.JSON_PROPERTY_ENABLED_BY_DEFAULT,
  CapabilityOption.JSON_PROPERTY_ENABLED,
  CapabilityOption.JSON_PROPERTY_SUPPORTS_WILDCARD
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-26T23:41:20.466109+03:00[Europe/Moscow]", comments = "Generator version: 7.6.0")
public class CapabilityOption {
  /**
   * Gets or Sets key
   */
  public enum KeyEnum {
    XCODE_5("XCODE_5"),
    
    XCODE_6("XCODE_6"),
    
    COMPLETE_PROTECTION("COMPLETE_PROTECTION"),
    
    PROTECTED_UNLESS_OPEN("PROTECTED_UNLESS_OPEN"),
    
    PROTECTED_UNTIL_FIRST_USER_AUTH("PROTECTED_UNTIL_FIRST_USER_AUTH"),
    
    PRIMARY_APP_CONSENT("PRIMARY_APP_CONSENT");

    private String value;

    KeyEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static KeyEnum fromValue(String value) {
      for (KeyEnum b : KeyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_KEY = "key";
  private KeyEnum key;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_ENABLED_BY_DEFAULT = "enabledByDefault";
  private Boolean enabledByDefault;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  private Boolean enabled;

  public static final String JSON_PROPERTY_SUPPORTS_WILDCARD = "supportsWildcard";
  private Boolean supportsWildcard;

  public CapabilityOption() { 
  }

  public CapabilityOption key(KeyEnum key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public KeyEnum getKey() {
    return key;
  }


  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKey(KeyEnum key) {
    this.key = key;
  }


  public CapabilityOption name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public CapabilityOption description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public CapabilityOption enabledByDefault(Boolean enabledByDefault) {
    this.enabledByDefault = enabledByDefault;
    return this;
  }

   /**
   * Get enabledByDefault
   * @return enabledByDefault
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENABLED_BY_DEFAULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabledByDefault() {
    return enabledByDefault;
  }


  @JsonProperty(JSON_PROPERTY_ENABLED_BY_DEFAULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabledByDefault(Boolean enabledByDefault) {
    this.enabledByDefault = enabledByDefault;
  }


  public CapabilityOption enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public CapabilityOption supportsWildcard(Boolean supportsWildcard) {
    this.supportsWildcard = supportsWildcard;
    return this;
  }

   /**
   * Get supportsWildcard
   * @return supportsWildcard
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPORTS_WILDCARD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSupportsWildcard() {
    return supportsWildcard;
  }


  @JsonProperty(JSON_PROPERTY_SUPPORTS_WILDCARD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupportsWildcard(Boolean supportsWildcard) {
    this.supportsWildcard = supportsWildcard;
  }


  /**
   * Return true if this CapabilityOption object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CapabilityOption capabilityOption = (CapabilityOption) o;
    return Objects.equals(this.key, capabilityOption.key) &&
        Objects.equals(this.name, capabilityOption.name) &&
        Objects.equals(this.description, capabilityOption.description) &&
        Objects.equals(this.enabledByDefault, capabilityOption.enabledByDefault) &&
        Objects.equals(this.enabled, capabilityOption.enabled) &&
        Objects.equals(this.supportsWildcard, capabilityOption.supportsWildcard);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, name, description, enabledByDefault, enabled, supportsWildcard);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CapabilityOption {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enabledByDefault: ").append(toIndentedString(enabledByDefault)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    supportsWildcard: ").append(toIndentedString(supportsWildcard)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

