/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.client.JSON;


/**
 * DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData
 */
@JsonPropertyOrder({
  DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.JSON_PROPERTY_BUNDLE_ID,
  DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.JSON_PROPERTY_EVENT,
  DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.JSON_PROPERTY_OS_VERSION,
  DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.JSON_PROPERTY_APP_VERSION,
  DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.JSON_PROPERTY_WRITES_CAUSED,
  DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.JSON_PROPERTY_DEVICE_TYPE,
  DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.JSON_PROPERTY_PLATFORM_ARCHITECTURE,
  DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.JSON_PROPERTY_EVENT_DETAIL,
  DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.JSON_PROPERTY_BUILD_VERSION
})
@JsonTypeName("diagnosticLogs_productData_inner_diagnosticLogs_inner_diagnosticMetaData")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-26T23:41:20.466109+03:00[Europe/Moscow]", comments = "Generator version: 7.6.0")
public class DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData {
  public static final String JSON_PROPERTY_BUNDLE_ID = "bundleId";
  private String bundleId;

  public static final String JSON_PROPERTY_EVENT = "event";
  private String event;

  public static final String JSON_PROPERTY_OS_VERSION = "osVersion";
  private String osVersion;

  public static final String JSON_PROPERTY_APP_VERSION = "appVersion";
  private String appVersion;

  public static final String JSON_PROPERTY_WRITES_CAUSED = "writesCaused";
  private String writesCaused;

  public static final String JSON_PROPERTY_DEVICE_TYPE = "deviceType";
  private String deviceType;

  public static final String JSON_PROPERTY_PLATFORM_ARCHITECTURE = "platformArchitecture";
  private String platformArchitecture;

  public static final String JSON_PROPERTY_EVENT_DETAIL = "eventDetail";
  private String eventDetail;

  public static final String JSON_PROPERTY_BUILD_VERSION = "buildVersion";
  private String buildVersion;

  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData() { 
  }

  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData bundleId(String bundleId) {
    this.bundleId = bundleId;
    return this;
  }

   /**
   * Get bundleId
   * @return bundleId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUNDLE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBundleId() {
    return bundleId;
  }


  @JsonProperty(JSON_PROPERTY_BUNDLE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBundleId(String bundleId) {
    this.bundleId = bundleId;
  }


  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData event(String event) {
    this.event = event;
    return this;
  }

   /**
   * Get event
   * @return event
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEvent() {
    return event;
  }


  @JsonProperty(JSON_PROPERTY_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvent(String event) {
    this.event = event;
  }


  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData osVersion(String osVersion) {
    this.osVersion = osVersion;
    return this;
  }

   /**
   * Get osVersion
   * @return osVersion
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOsVersion() {
    return osVersion;
  }


  @JsonProperty(JSON_PROPERTY_OS_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsVersion(String osVersion) {
    this.osVersion = osVersion;
  }


  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData appVersion(String appVersion) {
    this.appVersion = appVersion;
    return this;
  }

   /**
   * Get appVersion
   * @return appVersion
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APP_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAppVersion() {
    return appVersion;
  }


  @JsonProperty(JSON_PROPERTY_APP_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppVersion(String appVersion) {
    this.appVersion = appVersion;
  }


  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData writesCaused(String writesCaused) {
    this.writesCaused = writesCaused;
    return this;
  }

   /**
   * Get writesCaused
   * @return writesCaused
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WRITES_CAUSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWritesCaused() {
    return writesCaused;
  }


  @JsonProperty(JSON_PROPERTY_WRITES_CAUSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWritesCaused(String writesCaused) {
    this.writesCaused = writesCaused;
  }


  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData deviceType(String deviceType) {
    this.deviceType = deviceType;
    return this;
  }

   /**
   * Get deviceType
   * @return deviceType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVICE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeviceType() {
    return deviceType;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceType(String deviceType) {
    this.deviceType = deviceType;
  }


  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData platformArchitecture(String platformArchitecture) {
    this.platformArchitecture = platformArchitecture;
    return this;
  }

   /**
   * Get platformArchitecture
   * @return platformArchitecture
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLATFORM_ARCHITECTURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPlatformArchitecture() {
    return platformArchitecture;
  }


  @JsonProperty(JSON_PROPERTY_PLATFORM_ARCHITECTURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlatformArchitecture(String platformArchitecture) {
    this.platformArchitecture = platformArchitecture;
  }


  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData eventDetail(String eventDetail) {
    this.eventDetail = eventDetail;
    return this;
  }

   /**
   * Get eventDetail
   * @return eventDetail
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEventDetail() {
    return eventDetail;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventDetail(String eventDetail) {
    this.eventDetail = eventDetail;
  }


  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData buildVersion(String buildVersion) {
    this.buildVersion = buildVersion;
    return this;
  }

   /**
   * Get buildVersion
   * @return buildVersion
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUILD_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBuildVersion() {
    return buildVersion;
  }


  @JsonProperty(JSON_PROPERTY_BUILD_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuildVersion(String buildVersion) {
    this.buildVersion = buildVersion;
  }


  /**
   * Return true if this diagnosticLogs_productData_inner_diagnosticLogs_inner_diagnosticMetaData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData diagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData = (DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData) o;
    return Objects.equals(this.bundleId, diagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.bundleId) &&
        Objects.equals(this.event, diagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.event) &&
        Objects.equals(this.osVersion, diagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.osVersion) &&
        Objects.equals(this.appVersion, diagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.appVersion) &&
        Objects.equals(this.writesCaused, diagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.writesCaused) &&
        Objects.equals(this.deviceType, diagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.deviceType) &&
        Objects.equals(this.platformArchitecture, diagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.platformArchitecture) &&
        Objects.equals(this.eventDetail, diagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.eventDetail) &&
        Objects.equals(this.buildVersion, diagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.buildVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bundleId, event, osVersion, appVersion, writesCaused, deviceType, platformArchitecture, eventDetail, buildVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData {\n");
    sb.append("    bundleId: ").append(toIndentedString(bundleId)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    osVersion: ").append(toIndentedString(osVersion)).append("\n");
    sb.append("    appVersion: ").append(toIndentedString(appVersion)).append("\n");
    sb.append("    writesCaused: ").append(toIndentedString(writesCaused)).append("\n");
    sb.append("    deviceType: ").append(toIndentedString(deviceType)).append("\n");
    sb.append("    platformArchitecture: ").append(toIndentedString(platformArchitecture)).append("\n");
    sb.append("    eventDetail: ").append(toIndentedString(eventDetail)).append("\n");
    sb.append("    buildVersion: ").append(toIndentedString(buildVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

