/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.client.JSON;


/**
 * DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner
 */
@JsonPropertyOrder({
  DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner.JSON_PROPERTY_CALL_STACK_PER_THREAD,
  DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner.JSON_PROPERTY_CALL_STACKS
})
@JsonTypeName("diagnosticLogs_productData_inner_diagnosticLogs_inner_callStackTree_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-26T23:41:20.466109+03:00[Europe/Moscow]", comments = "Generator version: 7.6.0")
public class DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner {
  public static final String JSON_PROPERTY_CALL_STACK_PER_THREAD = "callStackPerThread";
  private Boolean callStackPerThread;

  public static final String JSON_PROPERTY_CALL_STACKS = "callStacks";
  private List<DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner> callStacks = new ArrayList<>();

  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner() { 
  }

  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner callStackPerThread(Boolean callStackPerThread) {
    this.callStackPerThread = callStackPerThread;
    return this;
  }

   /**
   * Get callStackPerThread
   * @return callStackPerThread
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CALL_STACK_PER_THREAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCallStackPerThread() {
    return callStackPerThread;
  }


  @JsonProperty(JSON_PROPERTY_CALL_STACK_PER_THREAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallStackPerThread(Boolean callStackPerThread) {
    this.callStackPerThread = callStackPerThread;
  }


  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner callStacks(List<DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner> callStacks) {
    this.callStacks = callStacks;
    return this;
  }

  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner addCallStacksItem(DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner callStacksItem) {
    if (this.callStacks == null) {
      this.callStacks = new ArrayList<>();
    }
    this.callStacks.add(callStacksItem);
    return this;
  }

   /**
   * Get callStacks
   * @return callStacks
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CALL_STACKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner> getCallStacks() {
    return callStacks;
  }


  @JsonProperty(JSON_PROPERTY_CALL_STACKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallStacks(List<DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner> callStacks) {
    this.callStacks = callStacks;
  }


  /**
   * Return true if this diagnosticLogs_productData_inner_diagnosticLogs_inner_callStackTree_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner diagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner = (DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner) o;
    return Objects.equals(this.callStackPerThread, diagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner.callStackPerThread) &&
        Objects.equals(this.callStacks, diagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner.callStacks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callStackPerThread, callStacks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner {\n");
    sb.append("    callStackPerThread: ").append(toIndentedString(callStackPerThread)).append("\n");
    sb.append("    callStacks: ").append(toIndentedString(callStacks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

