/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.client.model.GameCenterLeaderboardSetImageCreateRequestDataRelationshipsGameCenterLeaderboardSetLocalization;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.client.JSON;


/**
 * GameCenterLeaderboardSetImageCreateRequestDataRelationships
 */
@JsonPropertyOrder({
  GameCenterLeaderboardSetImageCreateRequestDataRelationships.JSON_PROPERTY_GAME_CENTER_LEADERBOARD_SET_LOCALIZATION
})
@JsonTypeName("GameCenterLeaderboardSetImageCreateRequest_data_relationships")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-26T23:41:20.466109+03:00[Europe/Moscow]", comments = "Generator version: 7.6.0")
public class GameCenterLeaderboardSetImageCreateRequestDataRelationships {
  public static final String JSON_PROPERTY_GAME_CENTER_LEADERBOARD_SET_LOCALIZATION = "gameCenterLeaderboardSetLocalization";
  private GameCenterLeaderboardSetImageCreateRequestDataRelationshipsGameCenterLeaderboardSetLocalization gameCenterLeaderboardSetLocalization;

  public GameCenterLeaderboardSetImageCreateRequestDataRelationships() { 
  }

  public GameCenterLeaderboardSetImageCreateRequestDataRelationships gameCenterLeaderboardSetLocalization(GameCenterLeaderboardSetImageCreateRequestDataRelationshipsGameCenterLeaderboardSetLocalization gameCenterLeaderboardSetLocalization) {
    this.gameCenterLeaderboardSetLocalization = gameCenterLeaderboardSetLocalization;
    return this;
  }

   /**
   * Get gameCenterLeaderboardSetLocalization
   * @return gameCenterLeaderboardSetLocalization
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GAME_CENTER_LEADERBOARD_SET_LOCALIZATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public GameCenterLeaderboardSetImageCreateRequestDataRelationshipsGameCenterLeaderboardSetLocalization getGameCenterLeaderboardSetLocalization() {
    return gameCenterLeaderboardSetLocalization;
  }


  @JsonProperty(JSON_PROPERTY_GAME_CENTER_LEADERBOARD_SET_LOCALIZATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGameCenterLeaderboardSetLocalization(GameCenterLeaderboardSetImageCreateRequestDataRelationshipsGameCenterLeaderboardSetLocalization gameCenterLeaderboardSetLocalization) {
    this.gameCenterLeaderboardSetLocalization = gameCenterLeaderboardSetLocalization;
  }


  /**
   * Return true if this GameCenterLeaderboardSetImageCreateRequest_data_relationships object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameCenterLeaderboardSetImageCreateRequestDataRelationships gameCenterLeaderboardSetImageCreateRequestDataRelationships = (GameCenterLeaderboardSetImageCreateRequestDataRelationships) o;
    return Objects.equals(this.gameCenterLeaderboardSetLocalization, gameCenterLeaderboardSetImageCreateRequestDataRelationships.gameCenterLeaderboardSetLocalization);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gameCenterLeaderboardSetLocalization);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameCenterLeaderboardSetImageCreateRequestDataRelationships {\n");
    sb.append("    gameCenterLeaderboardSetLocalization: ").append(toIndentedString(gameCenterLeaderboardSetLocalization)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

