/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.client.JSON;


/**
 * MetricsInsightPopulationsInner
 */
@JsonPropertyOrder({
  MetricsInsightPopulationsInner.JSON_PROPERTY_DELTA_PERCENTAGE,
  MetricsInsightPopulationsInner.JSON_PROPERTY_PERCENTILE,
  MetricsInsightPopulationsInner.JSON_PROPERTY_SUMMARY_STRING,
  MetricsInsightPopulationsInner.JSON_PROPERTY_REFERENCE_AVERAGE_VALUE,
  MetricsInsightPopulationsInner.JSON_PROPERTY_LATEST_VERSION_VALUE,
  MetricsInsightPopulationsInner.JSON_PROPERTY_DEVICE
})
@JsonTypeName("MetricsInsight_populations_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-26T23:41:20.466109+03:00[Europe/Moscow]", comments = "Generator version: 7.6.0")
public class MetricsInsightPopulationsInner {
  public static final String JSON_PROPERTY_DELTA_PERCENTAGE = "deltaPercentage";
  private BigDecimal deltaPercentage;

  public static final String JSON_PROPERTY_PERCENTILE = "percentile";
  private String percentile;

  public static final String JSON_PROPERTY_SUMMARY_STRING = "summaryString";
  private String summaryString;

  public static final String JSON_PROPERTY_REFERENCE_AVERAGE_VALUE = "referenceAverageValue";
  private BigDecimal referenceAverageValue;

  public static final String JSON_PROPERTY_LATEST_VERSION_VALUE = "latestVersionValue";
  private BigDecimal latestVersionValue;

  public static final String JSON_PROPERTY_DEVICE = "device";
  private String device;

  public MetricsInsightPopulationsInner() { 
  }

  public MetricsInsightPopulationsInner deltaPercentage(BigDecimal deltaPercentage) {
    this.deltaPercentage = deltaPercentage;
    return this;
  }

   /**
   * Get deltaPercentage
   * @return deltaPercentage
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELTA_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getDeltaPercentage() {
    return deltaPercentage;
  }


  @JsonProperty(JSON_PROPERTY_DELTA_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeltaPercentage(BigDecimal deltaPercentage) {
    this.deltaPercentage = deltaPercentage;
  }


  public MetricsInsightPopulationsInner percentile(String percentile) {
    this.percentile = percentile;
    return this;
  }

   /**
   * Get percentile
   * @return percentile
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERCENTILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPercentile() {
    return percentile;
  }


  @JsonProperty(JSON_PROPERTY_PERCENTILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPercentile(String percentile) {
    this.percentile = percentile;
  }


  public MetricsInsightPopulationsInner summaryString(String summaryString) {
    this.summaryString = summaryString;
    return this;
  }

   /**
   * Get summaryString
   * @return summaryString
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARY_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSummaryString() {
    return summaryString;
  }


  @JsonProperty(JSON_PROPERTY_SUMMARY_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSummaryString(String summaryString) {
    this.summaryString = summaryString;
  }


  public MetricsInsightPopulationsInner referenceAverageValue(BigDecimal referenceAverageValue) {
    this.referenceAverageValue = referenceAverageValue;
    return this;
  }

   /**
   * Get referenceAverageValue
   * @return referenceAverageValue
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERENCE_AVERAGE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getReferenceAverageValue() {
    return referenceAverageValue;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE_AVERAGE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferenceAverageValue(BigDecimal referenceAverageValue) {
    this.referenceAverageValue = referenceAverageValue;
  }


  public MetricsInsightPopulationsInner latestVersionValue(BigDecimal latestVersionValue) {
    this.latestVersionValue = latestVersionValue;
    return this;
  }

   /**
   * Get latestVersionValue
   * @return latestVersionValue
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LATEST_VERSION_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLatestVersionValue() {
    return latestVersionValue;
  }


  @JsonProperty(JSON_PROPERTY_LATEST_VERSION_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatestVersionValue(BigDecimal latestVersionValue) {
    this.latestVersionValue = latestVersionValue;
  }


  public MetricsInsightPopulationsInner device(String device) {
    this.device = device;
    return this;
  }

   /**
   * Get device
   * @return device
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDevice() {
    return device;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevice(String device) {
    this.device = device;
  }


  /**
   * Return true if this MetricsInsight_populations_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetricsInsightPopulationsInner metricsInsightPopulationsInner = (MetricsInsightPopulationsInner) o;
    return Objects.equals(this.deltaPercentage, metricsInsightPopulationsInner.deltaPercentage) &&
        Objects.equals(this.percentile, metricsInsightPopulationsInner.percentile) &&
        Objects.equals(this.summaryString, metricsInsightPopulationsInner.summaryString) &&
        Objects.equals(this.referenceAverageValue, metricsInsightPopulationsInner.referenceAverageValue) &&
        Objects.equals(this.latestVersionValue, metricsInsightPopulationsInner.latestVersionValue) &&
        Objects.equals(this.device, metricsInsightPopulationsInner.device);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deltaPercentage, percentile, summaryString, referenceAverageValue, latestVersionValue, device);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetricsInsightPopulationsInner {\n");
    sb.append("    deltaPercentage: ").append(toIndentedString(deltaPercentage)).append("\n");
    sb.append("    percentile: ").append(toIndentedString(percentile)).append("\n");
    sb.append("    summaryString: ").append(toIndentedString(summaryString)).append("\n");
    sb.append("    referenceAverageValue: ").append(toIndentedString(referenceAverageValue)).append("\n");
    sb.append("    latestVersionValue: ").append(toIndentedString(latestVersionValue)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

