/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.client.JSON;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ScreenshotDisplayType
 */
public enum ScreenshotDisplayType {
  
  APP_IPHONE_67("APP_IPHONE_67"),
  
  APP_IPHONE_61("APP_IPHONE_61"),
  
  APP_IPHONE_65("APP_IPHONE_65"),
  
  APP_IPHONE_58("APP_IPHONE_58"),
  
  APP_IPHONE_55("APP_IPHONE_55"),
  
  APP_IPHONE_47("APP_IPHONE_47"),
  
  APP_IPHONE_40("APP_IPHONE_40"),
  
  APP_IPHONE_35("APP_IPHONE_35"),
  
  APP_IPAD_PRO_3GEN_129("APP_IPAD_PRO_3GEN_129"),
  
  APP_IPAD_PRO_3GEN_11("APP_IPAD_PRO_3GEN_11"),
  
  APP_IPAD_PRO_129("APP_IPAD_PRO_129"),
  
  APP_IPAD_105("APP_IPAD_105"),
  
  APP_IPAD_97("APP_IPAD_97"),
  
  APP_DESKTOP("APP_DESKTOP"),
  
  APP_WATCH_ULTRA("APP_WATCH_ULTRA"),
  
  APP_WATCH_SERIES_7("APP_WATCH_SERIES_7"),
  
  APP_WATCH_SERIES_4("APP_WATCH_SERIES_4"),
  
  APP_WATCH_SERIES_3("APP_WATCH_SERIES_3"),
  
  APP_APPLE_TV("APP_APPLE_TV"),
  
  APP_APPLE_VISION_PRO("APP_APPLE_VISION_PRO"),
  
  IMESSAGE_APP_IPHONE_67("IMESSAGE_APP_IPHONE_67"),
  
  IMESSAGE_APP_IPHONE_61("IMESSAGE_APP_IPHONE_61"),
  
  IMESSAGE_APP_IPHONE_65("IMESSAGE_APP_IPHONE_65"),
  
  IMESSAGE_APP_IPHONE_58("IMESSAGE_APP_IPHONE_58"),
  
  IMESSAGE_APP_IPHONE_55("IMESSAGE_APP_IPHONE_55"),
  
  IMESSAGE_APP_IPHONE_47("IMESSAGE_APP_IPHONE_47"),
  
  IMESSAGE_APP_IPHONE_40("IMESSAGE_APP_IPHONE_40"),
  
  IMESSAGE_APP_IPAD_PRO_3GEN_129("IMESSAGE_APP_IPAD_PRO_3GEN_129"),
  
  IMESSAGE_APP_IPAD_PRO_3GEN_11("IMESSAGE_APP_IPAD_PRO_3GEN_11"),
  
  IMESSAGE_APP_IPAD_PRO_129("IMESSAGE_APP_IPAD_PRO_129"),
  
  IMESSAGE_APP_IPAD_105("IMESSAGE_APP_IPAD_105"),
  
  IMESSAGE_APP_IPAD_97("IMESSAGE_APP_IPAD_97");

  private String value;

  ScreenshotDisplayType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ScreenshotDisplayType fromValue(String value) {
    for (ScreenshotDisplayType b : ScreenshotDisplayType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

