/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.*;
import org.openapitools.client.auth.*;
import org.openapitools.client.model.AppClipAppStoreReviewDetailCreateRequest;
import org.openapitools.client.model.AppClipAppStoreReviewDetailResponse;
import org.openapitools.client.model.AppClipAppStoreReviewDetailUpdateRequest;
import org.openapitools.client.model.ErrorResponse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppClipAppStoreReviewDetailsApi
 */
public class AppClipAppStoreReviewDetailsApiTest {

    private final AppClipAppStoreReviewDetailsApi api = new AppClipAppStoreReviewDetailsApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appClipAppStoreReviewDetailsCreateInstanceTest() throws ApiException {
        //AppClipAppStoreReviewDetailCreateRequest appClipAppStoreReviewDetailCreateRequest = null;
        //AppClipAppStoreReviewDetailResponse response = api.appClipAppStoreReviewDetailsCreateInstance(appClipAppStoreReviewDetailCreateRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appClipAppStoreReviewDetailsGetInstanceTest() throws ApiException {
        //String id = null;
        //List<String> fieldsAppClipAppStoreReviewDetails = null;
        //List<String> include = null;
        //AppClipAppStoreReviewDetailResponse response = api.appClipAppStoreReviewDetailsGetInstance(id, fieldsAppClipAppStoreReviewDetails, include);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appClipAppStoreReviewDetailsUpdateInstanceTest() throws ApiException {
        //String id = null;
        //AppClipAppStoreReviewDetailUpdateRequest appClipAppStoreReviewDetailUpdateRequest = null;
        //AppClipAppStoreReviewDetailResponse response = api.appClipAppStoreReviewDetailsUpdateInstance(id, appClipAppStoreReviewDetailUpdateRequest);
        // TODO: test validations
    }

}
