/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.*;
import org.openapitools.client.auth.*;
import org.openapitools.client.model.AppPreviewSetsResponse;
import org.openapitools.client.model.AppScreenshotSetsResponse;
import org.openapitools.client.model.AppStoreVersionExperimentTreatmentLocalizationCreateRequest;
import org.openapitools.client.model.AppStoreVersionExperimentTreatmentLocalizationResponse;
import org.openapitools.client.model.ErrorResponse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppStoreVersionExperimentTreatmentLocalizationsApi
 */
public class AppStoreVersionExperimentTreatmentLocalizationsApiTest {

    private final AppStoreVersionExperimentTreatmentLocalizationsApi api = new AppStoreVersionExperimentTreatmentLocalizationsApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appStoreVersionExperimentTreatmentLocalizationsAppPreviewSetsGetToManyRelatedTest() throws ApiException {
        //String id = null;
        //List<String> filterPreviewType = null;
        //List<String> filterAppCustomProductPageLocalization = null;
        //List<String> filterAppStoreVersionLocalization = null;
        //List<String> fieldsAppCustomProductPageLocalizations = null;
        //List<String> fieldsAppStoreVersionExperimentTreatmentLocalizations = null;
        //List<String> fieldsAppPreviews = null;
        //List<String> fieldsAppPreviewSets = null;
        //List<String> fieldsAppStoreVersionLocalizations = null;
        //Integer limit = null;
        //Integer limitAppPreviews = null;
        //List<String> include = null;
        //AppPreviewSetsResponse response = api.appStoreVersionExperimentTreatmentLocalizationsAppPreviewSetsGetToManyRelated(id, filterPreviewType, filterAppCustomProductPageLocalization, filterAppStoreVersionLocalization, fieldsAppCustomProductPageLocalizations, fieldsAppStoreVersionExperimentTreatmentLocalizations, fieldsAppPreviews, fieldsAppPreviewSets, fieldsAppStoreVersionLocalizations, limit, limitAppPreviews, include);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appStoreVersionExperimentTreatmentLocalizationsAppScreenshotSetsGetToManyRelatedTest() throws ApiException {
        //String id = null;
        //List<String> filterScreenshotDisplayType = null;
        //List<String> filterAppCustomProductPageLocalization = null;
        //List<String> filterAppStoreVersionLocalization = null;
        //List<String> fieldsAppScreenshotSets = null;
        //List<String> fieldsAppCustomProductPageLocalizations = null;
        //List<String> fieldsAppStoreVersionExperimentTreatmentLocalizations = null;
        //List<String> fieldsAppScreenshots = null;
        //List<String> fieldsAppStoreVersionLocalizations = null;
        //Integer limit = null;
        //Integer limitAppScreenshots = null;
        //List<String> include = null;
        //AppScreenshotSetsResponse response = api.appStoreVersionExperimentTreatmentLocalizationsAppScreenshotSetsGetToManyRelated(id, filterScreenshotDisplayType, filterAppCustomProductPageLocalization, filterAppStoreVersionLocalization, fieldsAppScreenshotSets, fieldsAppCustomProductPageLocalizations, fieldsAppStoreVersionExperimentTreatmentLocalizations, fieldsAppScreenshots, fieldsAppStoreVersionLocalizations, limit, limitAppScreenshots, include);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appStoreVersionExperimentTreatmentLocalizationsCreateInstanceTest() throws ApiException {
        //AppStoreVersionExperimentTreatmentLocalizationCreateRequest appStoreVersionExperimentTreatmentLocalizationCreateRequest = null;
        //AppStoreVersionExperimentTreatmentLocalizationResponse response = api.appStoreVersionExperimentTreatmentLocalizationsCreateInstance(appStoreVersionExperimentTreatmentLocalizationCreateRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appStoreVersionExperimentTreatmentLocalizationsDeleteInstanceTest() throws ApiException {
        //String id = null;
        //api.appStoreVersionExperimentTreatmentLocalizationsDeleteInstance(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appStoreVersionExperimentTreatmentLocalizationsGetInstanceTest() throws ApiException {
        //String id = null;
        //List<String> fieldsAppStoreVersionExperimentTreatmentLocalizations = null;
        //List<String> include = null;
        //List<String> fieldsAppScreenshotSets = null;
        //List<String> fieldsAppPreviewSets = null;
        //Integer limitAppPreviewSets = null;
        //Integer limitAppScreenshotSets = null;
        //AppStoreVersionExperimentTreatmentLocalizationResponse response = api.appStoreVersionExperimentTreatmentLocalizationsGetInstance(id, fieldsAppStoreVersionExperimentTreatmentLocalizations, include, fieldsAppScreenshotSets, fieldsAppPreviewSets, limitAppPreviewSets, limitAppScreenshotSets);
        // TODO: test validations
    }

}
