/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.*;
import org.openapitools.client.auth.*;
import org.openapitools.client.model.CiMacOsVersionResponse;
import org.openapitools.client.model.CiMacOsVersionsResponse;
import org.openapitools.client.model.CiXcodeVersionsResponse;
import org.openapitools.client.model.ErrorResponse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CiMacOsVersionsApi
 */
public class CiMacOsVersionsApiTest {

    private final CiMacOsVersionsApi api = new CiMacOsVersionsApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ciMacOsVersionsGetCollectionTest() throws ApiException {
        //List<String> fieldsCiMacOsVersions = null;
        //Integer limit = null;
        //List<String> include = null;
        //List<String> fieldsCiXcodeVersions = null;
        //Integer limitXcodeVersions = null;
        //CiMacOsVersionsResponse response = api.ciMacOsVersionsGetCollection(fieldsCiMacOsVersions, limit, include, fieldsCiXcodeVersions, limitXcodeVersions);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ciMacOsVersionsGetInstanceTest() throws ApiException {
        //String id = null;
        //List<String> fieldsCiMacOsVersions = null;
        //List<String> include = null;
        //List<String> fieldsCiXcodeVersions = null;
        //Integer limitXcodeVersions = null;
        //CiMacOsVersionResponse response = api.ciMacOsVersionsGetInstance(id, fieldsCiMacOsVersions, include, fieldsCiXcodeVersions, limitXcodeVersions);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ciMacOsVersionsXcodeVersionsGetToManyRelatedTest() throws ApiException {
        //String id = null;
        //List<String> fieldsCiXcodeVersions = null;
        //List<String> fieldsCiMacOsVersions = null;
        //Integer limit = null;
        //Integer limitMacOsVersions = null;
        //List<String> include = null;
        //CiXcodeVersionsResponse response = api.ciMacOsVersionsXcodeVersionsGetToManyRelated(id, fieldsCiXcodeVersions, fieldsCiMacOsVersions, limit, limitMacOsVersions, include);
        // TODO: test validations
    }

}
