/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.*;
import org.openapitools.client.auth.*;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.GameCenterAchievementReleasesResponse;
import org.openapitools.client.model.GameCenterAchievementsResponse;
import org.openapitools.client.model.GameCenterAppVersionsResponse;
import org.openapitools.client.model.GameCenterDetailCreateRequest;
import org.openapitools.client.model.GameCenterDetailGameCenterAchievementsLinkagesRequest;
import org.openapitools.client.model.GameCenterDetailGameCenterAchievementsLinkagesResponse;
import org.openapitools.client.model.GameCenterDetailGameCenterLeaderboardSetsLinkagesRequest;
import org.openapitools.client.model.GameCenterDetailGameCenterLeaderboardSetsLinkagesResponse;
import org.openapitools.client.model.GameCenterDetailGameCenterLeaderboardsLinkagesRequest;
import org.openapitools.client.model.GameCenterDetailGameCenterLeaderboardsLinkagesResponse;
import org.openapitools.client.model.GameCenterDetailResponse;
import org.openapitools.client.model.GameCenterDetailUpdateRequest;
import org.openapitools.client.model.GameCenterGroupResponse;
import org.openapitools.client.model.GameCenterLeaderboardReleasesResponse;
import org.openapitools.client.model.GameCenterLeaderboardSetReleasesResponse;
import org.openapitools.client.model.GameCenterLeaderboardSetsResponse;
import org.openapitools.client.model.GameCenterLeaderboardsResponse;
import org.openapitools.client.model.GameCenterMatchmakingAppRequestsV1MetricResponse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GameCenterDetailsApi
 */
public class GameCenterDetailsApiTest {

    private final GameCenterDetailsApi api = new GameCenterDetailsApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsAchievementReleasesGetToManyRelatedTest() throws ApiException {
        //String id = null;
        //List<String> filterLive = null;
        //List<String> filterGameCenterAchievement = null;
        //List<String> fieldsGameCenterAchievementReleases = null;
        //List<String> fieldsGameCenterDetails = null;
        //List<String> fieldsGameCenterAchievements = null;
        //Integer limit = null;
        //List<String> include = null;
        //GameCenterAchievementReleasesResponse response = api.gameCenterDetailsAchievementReleasesGetToManyRelated(id, filterLive, filterGameCenterAchievement, fieldsGameCenterAchievementReleases, fieldsGameCenterDetails, fieldsGameCenterAchievements, limit, include);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsClassicMatchmakingRequestsGetMetricsTest() throws ApiException {
        //String id = null;
        //String granularity = null;
        //Integer limit = null;
        //List<String> groupBy = null;
        //String filterResult = null;
        //List<String> sort = null;
        //GameCenterMatchmakingAppRequestsV1MetricResponse response = api.gameCenterDetailsClassicMatchmakingRequestsGetMetrics(id, granularity, limit, groupBy, filterResult, sort);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsCreateInstanceTest() throws ApiException {
        //GameCenterDetailCreateRequest gameCenterDetailCreateRequest = null;
        //GameCenterDetailResponse response = api.gameCenterDetailsCreateInstance(gameCenterDetailCreateRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsGameCenterAchievementsGetToManyRelatedTest() throws ApiException {
        //String id = null;
        //List<String> filterArchived = null;
        //List<String> filterReferenceName = null;
        //List<String> filterId = null;
        //List<String> fieldsGameCenterAchievementReleases = null;
        //List<String> fieldsGameCenterGroups = null;
        //List<String> fieldsGameCenterDetails = null;
        //List<String> fieldsGameCenterAchievementLocalizations = null;
        //List<String> fieldsGameCenterAchievements = null;
        //Integer limit = null;
        //Integer limitLocalizations = null;
        //Integer limitReleases = null;
        //List<String> include = null;
        //GameCenterAchievementsResponse response = api.gameCenterDetailsGameCenterAchievementsGetToManyRelated(id, filterArchived, filterReferenceName, filterId, fieldsGameCenterAchievementReleases, fieldsGameCenterGroups, fieldsGameCenterDetails, fieldsGameCenterAchievementLocalizations, fieldsGameCenterAchievements, limit, limitLocalizations, limitReleases, include);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsGameCenterAchievementsGetToManyRelationshipTest() throws ApiException {
        //String id = null;
        //Integer limit = null;
        //GameCenterDetailGameCenterAchievementsLinkagesResponse response = api.gameCenterDetailsGameCenterAchievementsGetToManyRelationship(id, limit);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsGameCenterAchievementsReplaceToManyRelationshipTest() throws ApiException {
        //String id = null;
        //GameCenterDetailGameCenterAchievementsLinkagesRequest gameCenterDetailGameCenterAchievementsLinkagesRequest = null;
        //api.gameCenterDetailsGameCenterAchievementsReplaceToManyRelationship(id, gameCenterDetailGameCenterAchievementsLinkagesRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsGameCenterAppVersionsGetToManyRelatedTest() throws ApiException {
        //String id = null;
        //List<String> filterEnabled = null;
        //List<String> fieldsAppStoreVersions = null;
        //List<String> fieldsGameCenterAppVersions = null;
        //Integer limit = null;
        //Integer limitCompatibilityVersions = null;
        //List<String> include = null;
        //GameCenterAppVersionsResponse response = api.gameCenterDetailsGameCenterAppVersionsGetToManyRelated(id, filterEnabled, fieldsAppStoreVersions, fieldsGameCenterAppVersions, limit, limitCompatibilityVersions, include);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsGameCenterGroupGetToOneRelatedTest() throws ApiException {
        //String id = null;
        //List<String> fieldsGameCenterLeaderboardSets = null;
        //List<String> fieldsGameCenterGroups = null;
        //List<String> fieldsGameCenterDetails = null;
        //List<String> fieldsGameCenterLeaderboards = null;
        //List<String> fieldsGameCenterAchievements = null;
        //Integer limitGameCenterDetails = null;
        //Integer limitGameCenterLeaderboards = null;
        //Integer limitGameCenterLeaderboardSets = null;
        //Integer limitGameCenterAchievements = null;
        //List<String> include = null;
        //GameCenterGroupResponse response = api.gameCenterDetailsGameCenterGroupGetToOneRelated(id, fieldsGameCenterLeaderboardSets, fieldsGameCenterGroups, fieldsGameCenterDetails, fieldsGameCenterLeaderboards, fieldsGameCenterAchievements, limitGameCenterDetails, limitGameCenterLeaderboards, limitGameCenterLeaderboardSets, limitGameCenterAchievements, include);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsGameCenterLeaderboardSetsGetToManyRelatedTest() throws ApiException {
        //String id = null;
        //List<String> filterReferenceName = null;
        //List<String> filterId = null;
        //List<String> fieldsGameCenterLeaderboardSetLocalizations = null;
        //List<String> fieldsGameCenterLeaderboardSetReleases = null;
        //List<String> fieldsGameCenterLeaderboardSets = null;
        //List<String> fieldsGameCenterGroups = null;
        //List<String> fieldsGameCenterDetails = null;
        //List<String> fieldsGameCenterLeaderboards = null;
        //Integer limit = null;
        //Integer limitLocalizations = null;
        //Integer limitGameCenterLeaderboards = null;
        //Integer limitReleases = null;
        //List<String> include = null;
        //GameCenterLeaderboardSetsResponse response = api.gameCenterDetailsGameCenterLeaderboardSetsGetToManyRelated(id, filterReferenceName, filterId, fieldsGameCenterLeaderboardSetLocalizations, fieldsGameCenterLeaderboardSetReleases, fieldsGameCenterLeaderboardSets, fieldsGameCenterGroups, fieldsGameCenterDetails, fieldsGameCenterLeaderboards, limit, limitLocalizations, limitGameCenterLeaderboards, limitReleases, include);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsGameCenterLeaderboardSetsGetToManyRelationshipTest() throws ApiException {
        //String id = null;
        //Integer limit = null;
        //GameCenterDetailGameCenterLeaderboardSetsLinkagesResponse response = api.gameCenterDetailsGameCenterLeaderboardSetsGetToManyRelationship(id, limit);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsGameCenterLeaderboardSetsReplaceToManyRelationshipTest() throws ApiException {
        //String id = null;
        //GameCenterDetailGameCenterLeaderboardSetsLinkagesRequest gameCenterDetailGameCenterLeaderboardSetsLinkagesRequest = null;
        //api.gameCenterDetailsGameCenterLeaderboardSetsReplaceToManyRelationship(id, gameCenterDetailGameCenterLeaderboardSetsLinkagesRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsGameCenterLeaderboardsGetToManyRelatedTest() throws ApiException {
        //String id = null;
        //List<String> filterArchived = null;
        //List<String> filterReferenceName = null;
        //List<String> filterId = null;
        //List<String> fieldsGameCenterLeaderboardLocalizations = null;
        //List<String> fieldsGameCenterLeaderboardSets = null;
        //List<String> fieldsGameCenterGroups = null;
        //List<String> fieldsGameCenterDetails = null;
        //List<String> fieldsGameCenterLeaderboards = null;
        //List<String> fieldsGameCenterLeaderboardReleases = null;
        //Integer limit = null;
        //Integer limitGameCenterLeaderboardSets = null;
        //Integer limitLocalizations = null;
        //Integer limitReleases = null;
        //List<String> include = null;
        //GameCenterLeaderboardsResponse response = api.gameCenterDetailsGameCenterLeaderboardsGetToManyRelated(id, filterArchived, filterReferenceName, filterId, fieldsGameCenterLeaderboardLocalizations, fieldsGameCenterLeaderboardSets, fieldsGameCenterGroups, fieldsGameCenterDetails, fieldsGameCenterLeaderboards, fieldsGameCenterLeaderboardReleases, limit, limitGameCenterLeaderboardSets, limitLocalizations, limitReleases, include);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsGameCenterLeaderboardsGetToManyRelationshipTest() throws ApiException {
        //String id = null;
        //Integer limit = null;
        //GameCenterDetailGameCenterLeaderboardsLinkagesResponse response = api.gameCenterDetailsGameCenterLeaderboardsGetToManyRelationship(id, limit);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsGameCenterLeaderboardsReplaceToManyRelationshipTest() throws ApiException {
        //String id = null;
        //GameCenterDetailGameCenterLeaderboardsLinkagesRequest gameCenterDetailGameCenterLeaderboardsLinkagesRequest = null;
        //api.gameCenterDetailsGameCenterLeaderboardsReplaceToManyRelationship(id, gameCenterDetailGameCenterLeaderboardsLinkagesRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsGetInstanceTest() throws ApiException {
        //String id = null;
        //List<String> fieldsGameCenterDetails = null;
        //List<String> include = null;
        //List<String> fieldsGameCenterAchievementReleases = null;
        //List<String> fieldsGameCenterLeaderboardSetReleases = null;
        //List<String> fieldsGameCenterLeaderboardSets = null;
        //List<String> fieldsGameCenterGroups = null;
        //List<String> fieldsGameCenterLeaderboards = null;
        //List<String> fieldsGameCenterAchievements = null;
        //List<String> fieldsGameCenterAppVersions = null;
        //List<String> fieldsGameCenterLeaderboardReleases = null;
        //Integer limitAchievementReleases = null;
        //Integer limitGameCenterAchievements = null;
        //Integer limitGameCenterAppVersions = null;
        //Integer limitGameCenterLeaderboardSets = null;
        //Integer limitGameCenterLeaderboards = null;
        //Integer limitLeaderboardReleases = null;
        //Integer limitLeaderboardSetReleases = null;
        //GameCenterDetailResponse response = api.gameCenterDetailsGetInstance(id, fieldsGameCenterDetails, include, fieldsGameCenterAchievementReleases, fieldsGameCenterLeaderboardSetReleases, fieldsGameCenterLeaderboardSets, fieldsGameCenterGroups, fieldsGameCenterLeaderboards, fieldsGameCenterAchievements, fieldsGameCenterAppVersions, fieldsGameCenterLeaderboardReleases, limitAchievementReleases, limitGameCenterAchievements, limitGameCenterAppVersions, limitGameCenterLeaderboardSets, limitGameCenterLeaderboards, limitLeaderboardReleases, limitLeaderboardSetReleases);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsLeaderboardReleasesGetToManyRelatedTest() throws ApiException {
        //String id = null;
        //List<String> filterLive = null;
        //List<String> filterGameCenterLeaderboard = null;
        //List<String> fieldsGameCenterDetails = null;
        //List<String> fieldsGameCenterLeaderboards = null;
        //List<String> fieldsGameCenterLeaderboardReleases = null;
        //Integer limit = null;
        //List<String> include = null;
        //GameCenterLeaderboardReleasesResponse response = api.gameCenterDetailsLeaderboardReleasesGetToManyRelated(id, filterLive, filterGameCenterLeaderboard, fieldsGameCenterDetails, fieldsGameCenterLeaderboards, fieldsGameCenterLeaderboardReleases, limit, include);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsLeaderboardSetReleasesGetToManyRelatedTest() throws ApiException {
        //String id = null;
        //List<String> filterLive = null;
        //List<String> filterGameCenterLeaderboardSet = null;
        //List<String> fieldsGameCenterLeaderboardSetReleases = null;
        //List<String> fieldsGameCenterLeaderboardSets = null;
        //List<String> fieldsGameCenterDetails = null;
        //Integer limit = null;
        //List<String> include = null;
        //GameCenterLeaderboardSetReleasesResponse response = api.gameCenterDetailsLeaderboardSetReleasesGetToManyRelated(id, filterLive, filterGameCenterLeaderboardSet, fieldsGameCenterLeaderboardSetReleases, fieldsGameCenterLeaderboardSets, fieldsGameCenterDetails, limit, include);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsRuleBasedMatchmakingRequestsGetMetricsTest() throws ApiException {
        //String id = null;
        //String granularity = null;
        //Integer limit = null;
        //List<String> groupBy = null;
        //String filterResult = null;
        //List<String> sort = null;
        //GameCenterMatchmakingAppRequestsV1MetricResponse response = api.gameCenterDetailsRuleBasedMatchmakingRequestsGetMetrics(id, granularity, limit, groupBy, filterResult, sort);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gameCenterDetailsUpdateInstanceTest() throws ApiException {
        //String id = null;
        //GameCenterDetailUpdateRequest gameCenterDetailUpdateRequest = null;
        //GameCenterDetailResponse response = api.gameCenterDetailsUpdateInstance(id, gameCenterDetailUpdateRequest);
        // TODO: test validations
    }

}
